- name: Install AWS CLI
  apt:
    name: awscli
    state: present

- name: Copy Script Template to Raspberry Pi
  template:
    src: aws-s3-sync.sh.j2
    dest: /srv/aws-s3-sync.sh
    mode: '0755'

- name: Configure AWS CLI
  expect:
    command: aws configure
    responses:
      'AWS Access Key ID': "{{ env_vars.AWS_NAS_S3_ACCESS_KEY_ID }}"
      'AWS Secret Access Key': "{{ env_vars.AWS_NAS_S3_SECRET_ACCESS_KEY }}"
      'Default region name': "{{ env_vars.AWS_NAS_S3_REGION }}"
      'Default output format': ""
    timeout: 10

- name: Add Cron Job to Run Script Every Minute
  cron:
    name: "Run AWS Script"
    minute: "*"
    job: |
      cd /srv && ./aws-s3-sync.sh >> "/srv/{{ env_vars.NAS_NAME }}/s3-upload-logs/log_$(date +\%Y\%m\%d).log" 2>&1
  become: yes

- name: Restart cron service
  become: yes
  service:
    name: cron
    state: restarted