- name: Create Portainer data directory
  file:
    path: /opt/portainer_data
    state: directory

- name: Run Portainer container
  docker_container:
    name: portainer
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer_data:/data
    restart_policy: always