- name: Load environment variables
  include_vars:
    file: .env
    name: env_vars

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release']
    state: present